name: dump-feishu-ids
on: workflow_dispatch    # 只手动运行
jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: 输出 base64
        run: |
          echo "BITABLE_ID=$(printf '%s' '${{ secrets.FEISHU_BITABLE_ID }}' | base64 -w0)"
          echo "TABLE_ID=$(printf '%s' '${{ secrets.FEISHU_TABLE_ID }}' | base64 -w0)"
